export const data=[
    { id:1,
      image:"https://images.urbndata.com/is/image/Anthropologie/79896379_006_b14?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
      model:"chair",
      namef:"Flo Occasional Chair",
      description:"A luxe rounded seat is encased by four gleaming metal legs - acting as the show-stopping pillars that highlight the opulent velvet texture. The rounded back sits suspended above the seat, fully upholstered in please-touch boucle, and ready for morning coffee breaks and afternoon reading sessions.",
      price:" 348",
      
    },
    { id:2,
        image:"https://images.urbndata.com/is/image/Anthropologie/54352182_014_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"chair",
        namef:"Heritage Dining Chair",
        description:"Featuring a low-profile back with a unique open design, this chair is both a modern and timeless choice for any table.",
        price:" 268",
        
      },

      { id:3,
        image:"https://images.urbndata.com/is/image/Anthropologie/80370257_030_b14?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"chair",
        namef:"Ossa Karissa Dining",
        description:"An intricately sculptured back sets the stage for this inviting seat, featuring a plush cushion and frame and legs crafted of natural wood.",
        price:" 548",
       
      },
      { id:4,
        image:"https://images.urbndata.com/is/image/Anthropologie/79896353_003_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"sofa",
        namef:"Sheba Sofa",
        description:"With its rounded, modern design, this plush respite instantly elevates any room with a striking silhouette, natural wooden legs, and linen-blend upholstery atop its curved frame.",
        price:" 1250",
      
      },
      { id:5,
        image:"https://images.urbndata.com/is/image/Anthropologie/63716716_032_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"sofa",
        namef:"Judarn Asymmetrical Serpentine Sofa",
        description:"Inspired by Italian design, this luxe respite instantly elevates any room with its striking asymmetrical silhouette, plush velvet seat, and tapestry-inspired upholstery atop its curved frame.",
        price:" 1500",
     
      },
      { id:6,
        image:"https://images.urbndata.com/is/image/Anthropologie/82979535_071_b14?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"sofa",
        namef:"Cecilia Willoughby Two-Cushion Sofa",
        description:"Reminiscent of the umbrellas that line the Amalfi Coast, this mixed-upholstered sofa features classic touches with hints of modern design. Its antique legs and elegant, scrolled arms beautifully highlight the striped two-cushion seat.",
        price:" 3500",
   
      },
      { id:7,
        image:"https://images.urbndata.com/is/image/Anthropologie/45206568AF_015_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"bed",
        namef:"Hemming Bed",
        description:"This modern, minimalist bed is accented with antique brass caps and an austere metal bar to define its sleek, organic oak veneer headboard and frame. For a plush addition, pair it with our custom-fit headboard cushion.",
        price:" 768",
      
      },
      { id:8,
        image:"https://images.urbndata.com/is/image/Anthropologie/54286000_047_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"bed",
        namef:"Rosalie Four-Poster Bed",
        description:"Accented by carved posters and a cloud-like headboard, this bed exudes a charm that matches farmhouse-style and eclectic bedrooms alike.",
        price:" 1698",
  
      },
      { id:9,
        image:"https://images.urbndata.com/is/image/Anthropologie/45205181AF_014_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"bed",
        namef:"Textured Trellis Bed",
        description:"Like the garden trellises that inspired its design, our Textured Trellis collection invites a fresh perspective into your home. Complete with a raised motif on its ash wood facade, the timelessness of this bed is found in both its details and stately silhouette.",
        price:" 838",
     
        
      },
      { id:10,
        image:"https://images.urbndata.com/is/image/Anthropologie/79681730_014_b15?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"table",
        namef:"Kanta Marble Coffee Table",
        description:"Crafted of pure marble, this stately coffee table lends a classical element to studies and living rooms alike.",
        price:" 1598",
    
      },
      { id:11,
        image:"https://images.urbndata.com/is/image/Anthropologie/79790622_014_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"table",
        namef:"Palma Reclaimed Coffee Table",
        description:"Invite an artistic appeal into a simple living or entertaining room with this U-shaped coffee table. Crafted of natural oak, it holds drinks and lamps while storing books and puzzles down below.",
        price:"1598",
      
      },
      { id:12,
        image:"https://images.urbndata.com/is/image/Anthropologie/79897450_023_b10?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"table",
        namef:"Infinity Glass Side Table",
        description:"Beautifully crafted of gleaming glass and smooth marble, this chic side table lends an effortless elegance to bedsides and couch ends alike.",
        price:" 368",
       
      },
      { id:13,
        image:"https://images.urbndata.com/is/image/Anthropologie/54740071_001_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"mirror",
        namef:"Perla Mirror",
        description:"Featuring an Art Deco-meets-modern design, this mirror is a beautiful addition to a bathroom, entryway, or bedroom.",
        price:" 358",
 
      },
      { id:14,
        image:"https://images.urbndata.com/is/image/Anthropologie/59947713_027_b15?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"mirror",
        namef:"Demeter Mirror",
        description:"With a beautiful antique brass finish, this mirror offers a timeless accent to a hallway, home office, or living room.",
        price:" 348",
      
      },
      { id:15,
        image:"https://images.urbndata.com/is/image/Anthropologie/60214129_027_b2?$an-category$&fit=constrain&fmt=webp&hei=1046&qlt=80&wid=698",
        model:"mirror",
        namef:"Joan Lucite and Brass Arched Mirror",
        description:"Whether hung over a bathroom vanity or an entryway console, this mirror lends a contemporary aesthetic to any space with its lucite frame and champagne-finished brass accents.",
        price:" 498",
     
      },
      { id:16,
        image:"https://images.urbndata.com/is/image/Anthropologie/67711747_001_b14?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"dresser",
        namef:"Aria Six-Drawer Dresser",
        description:"Complete with a rounded oak wood facade, dignified legs, and smooth resin knobs, the timelessness of the Aria Dresser is found in both its details and stately silhouette. Featuring six drawers for storage and a generous surface to place trinkets and fresh flowers, this functional piece lends a modern sophistication to your guest room or bedchamber.",
        price:" 1698",
        
      },
      { id:17,
        image:"https://images.urbndata.com/is/image/Anthropologie/54062328_001_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"dresser",
        namef:"Fern Storage Cabinet",
        description:"Behind its tempered glass doors, a collection of marble-topped drawers and ash wood shelves lend this cabinet ample storage space. Better yet? It features a useful cord escape, allowing you to place record players, lamps, and any other plug-in pieces within.",
        price:" 2698",
      
      },
      { id:18,
        image:"https://images.urbndata.com/is/image/Anthropologie/51832640_014_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"dresser",
        namef:"Wallace Cane and Oak Armoire",
        description:"With a gracefully arched silhouette, this armoire features a tactile facade crafted from oak veneer caning, resulting in a design that is worthy of your cherished wardrobe.",
        price:" 2998",
     
      },
      { id:19,
        image:"https://images.urbndata.com/is/image/Anthropologie/40800765_001_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"dresser",
        namef:"Odetta Nine-Drawer Dresser",
        description:"With an elevated grasscloth-inspired texture throughout, our Odetta collection is accented with elliptical brass and lucite knobs etched with the same fine detail as reflected in its veneer. Featuring nine drawers of generous storage, it's a welcome addition to any transitional bedroom space.",
        price:" 2498",
     
      },
      { id:20,
        image:"https://images.urbndata.com/is/image/Anthropologie/45206375AC_010_b?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=720",
        model:"dresser",
        namef:"Quincy Five-Drawer Dresser",
        description:"This mid-century-inspired silhouette features an external border element that frames its shape and tapers to the leg. Understated brass hardware complements the beautiful grain of the wood without clashing or distracting, while sculpted drawer fronts add a layer of texture that draws the eye.",
        price:" 998",
     
      }

]